app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  client-retry-number: 4
  client-retry-timeout: 30
  client-timeout: 30
  rate-limit: 5
  rate-durationinms: 60000

resilience4j.circuitbreaker:
  instances:
    breaker:
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 20
      slidingWindowSize: 20
      failureThreshold: 5s
resilience4j.retry:
  instances:
    retry:
      maxAttempts: 3
      waitDuration: 500

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: INTERNAL://localhost:9092
    template:
      default-topic: update-links
    consumer.properties:
      enable.autocommit: false
      auto.offset.reset: latest
      isolation.level: read_committed
      fetch.mit.bytes: 1024
      fetch.max.wait.ms: 10000
      max.poll.interval.ms: 10000
      max.poll.records: 10
  cloud.zookeeper:
    config.enabled: false
    connect-string: localhost:2181

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
